code completion
contiamo/rhombic pull request #30
Opened 2021-08-12 09:29 UTC by megaflo

This pr introduces a first version for code completion via antlr. Column names and tables are collected via a custom ast visitor.

2021-08-12 09:49 UTC, fabien0102 commented on src/antlr/CompletionsVisitor.ts
> + * The position for which to run completion will be identified via a special token (CARET: '<|>').
I'm not really fan of changing the grammar to have this special caret... The node range should be enough, so let's not mix everything.

Let's talk on this on Monday.

2021-08-13 09:28 UTC, chris-baynes commented
Since quite a bit of the diff is the generated code we could try `linguist-generated=true` on those files to improve readability of the PR, see https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/customizing-how-changed-files-appear-on-github
wdyt @megaflo?

2021-08-16 07:34 UTC, fabien0102 requested changes
This code completion logic should not leak inside the grammar

2021-08-17 09:37 UTC, megaflo commented
The approach has been changed to avoid grammar changes. Instead of parsing and checking a special token the visitor now identifies the cursor by a special string suffix ("_CURSOR_"). From the grammars/antlrs point of view this is just (part of) a regular identifier. Contrary to what I initially assumed the resulting code is not more complex (or hacky) than the token version, so I am happy with this change.

2021-09-16 11:03 UTC, micha-f commented
@megaflo Shall we close this one?

2021-09-16 11:14 UTC, megaflo commented
Yep :)

2021-09-16 11:14 UTC, closed without merging